### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by mamaracas** [lonelyplanet/react-validate-form#3]
https://github.com/lonelyplanet/react-validate-form/blob/master/src/validate.jsx#L1

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by vacas5** [comment]
should be fixed by #17
